# Generated by Django 3.0.8 on 2020-07-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yashuvim', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yashuv',
            old_name='Name',
            new_name='name',
        ),
    ]
