# Generated by Django 3.1.1 on 2020-09-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yashuvim', '0002_yashuv_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yashuv',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='yashuv',
            name='photo_main',
        ),
        migrations.AlterField(
            model_name='yashuv',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
