# Generated by Django 3.1.1 on 2020-09-27 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_instructor_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='password',
        ),
        migrations.AddField(
            model_name='instructor',
            name='id_number',
            field=models.CharField(default='', max_length=9, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 9', regex='^.{9}$')]),
            preserve_default=False,
        ),
    ]
