# Generated by Django 3.1.1 on 2020-09-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0003_auto_20200927_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='id_number',
        ),
        migrations.AddField(
            model_name='instructor',
            name='description',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
