# Generated by Django 3.1.1 on 2020-10-04 13:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yashuvim', '0003_auto_20200927_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('instructor', models.ForeignKey(limit_choices_to={'groups__name': 'Instructor'}, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_time', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', related_query_name='meeting', to='attendance.circle')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('full_name', models.CharField(max_length=64)),
                ('preferred_name', models.CharField(blank=True, max_length=64)),
                ('id_number', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 9', regex='^.{9}$')])),
                ('gender', models.CharField(choices=[('זכר', 'זכר'), ('נקבה', 'נקבה')], default='', max_length=4)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('allergys_to', models.CharField(blank=True, max_length=200)),
                ('shirt_size', models.CharField(blank=True, max_length=5)),
                ('youth_organization', models.CharField(blank=True, max_length=64)),
                ('hobbies', models.CharField(blank=True, max_length=200)),
                ('contact_name', models.CharField(default='', max_length=64)),
                ('contact_relation', models.CharField(default='', max_length=64)),
                ('contact_phone', models.CharField(default='', max_length=64)),
                ('yashuv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yashuvim.yashuv')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('attended', models.BooleanField(default=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', related_query_name='participation', to='attendance.meeting')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', related_query_name='participation', to='attendance.member')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='circle',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='circles', to='attendance.Member'),
        ),
        migrations.AddField(
            model_name='circle',
            name='yashuv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yashuvim.yashuv'),
        ),
    ]
