# Generated by Django 3.1.1 on 2020-09-22 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
     
        ('attendance', '0002_auto_20200922_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group'),
        ),
    ]
