# Generated by Django 3.1.1 on 2020-09-22 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yashuvim', '0002_yashuv_location'),
        ('attendance', '0004_auto_20200922_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='middle_name',
            new_name='youth_organization',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
        migrations.AddField(
            model_name='member',
            name='allergys_to',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='hobbies',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='shirt_size',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='member',
            name='yashuv',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='yashuvim.yashuv'),
            preserve_default=False,
        ),
    ]
