# Generated by Django 3.1.2 on 2020-10-11 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20201007_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='description',
        ),
        migrations.AlterField(
            model_name='member',
            name='id_number',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Id length has to be 9', regex='^.{9}$')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Phone length has to be 10', regex='^.{10}$')]),
        ),
    ]
