# Generated by Django 3.1.1 on 2020-09-26 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0005_auto_20200922_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'instructor'}, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
