# Generated by Django 3.1.1 on 2020-09-28 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20200927_1437'),
        ('attendance', '0003_auto_20200929_0113'),
    ]

    operations = [
    ]
