# Generated by Django 3.1.1 on 2020-09-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_merge_20200929_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circle',
            name='address',
        ),
        migrations.RemoveField(
            model_name='circle',
            name='photo_main',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date_time',
            field=models.DateField(),
        ),
    ]
